### ISSUE TITLE
Missing Multiplication Operator in Given Examples

### ISSUE THREAD

**Issue by aminemarref** [SJasoria/Reduce-Algebraic-Expressions#1]
Hello,

Thank you for the useful predicate. I was trying the example queries you provide in the main page and in the Readme file, but SWI Prolog does not work with some of them unless multiplication is expressed explicitely using the "*" operator. For example, the query "simplify(4a2b3+ 24+a+15+d, OutExpr)" fails but the query "simplify(4*a*2*b*3+ 24+a+15+d, OutExpr)" succeeds.

Before I look into the code, I thought it is easier to ask you whether or not multiplication has to be explicitly expressed using the "*" operator; and if that's the case, perhaps inject this operator in the given example queries wherever needed.

Many thanks.

**Comment by aminemarref** [comment]
Now that I have written the issue, I can see that some of the asterisks are omitted in my message, so perhaps, you did include them and this message editor is not being very cooperative.

**Comment by SJasoria** [comment]
Hi,

I looked up a bit. It turns out that * is an escape character, so a '\\' has to be used before it.

I've updated the readme. 

Many thanks for catching the nit
